@startuml
!theme cerulean
'https://plantuml.com/component-diagram

()HTTP

package "Books" {
	[BookController]
	[BookCollection]
	[BookCoverService]
	[BookRepository]
	[BookEventPublisher]
}

database "AWS" {
    [S3]
}

package "Enrichment" {
	[EnrichAddedBookEventListener]
	[BookEnrichmentDataRepository]
}

'relationships
HTTP -d-> [BookController]

[BookController] --> [BookCollection]
[BookController] --> [BookCoverService]
[BookCollection] --> [BookRepository]
[BookCollection] --> [BookEventPublisher]
[BookCoverService] --> [S3]

[BookEventPublisher] .- [EnrichAddedBookEventListener]

[EnrichAddedBookEventListener] --> [BookEnrichmentDataRepository]
[EnrichAddedBookEventListener] ---> [BookRepository]

@enduml
